--SQL Advance Case Study
   

--Q1--BEGIN 
/*1. List all the states in which we have customers who have bought cellphones 
from 2005 till today. */


	USE db_SQLCaseStudies;

	SELECT  DISTINCT B.STATE
	FROM FACT_TRANSACTIONS E
	INNER JOIN DIM_LOCATION B
	ON E.IDLOCATION = B.IDLOCATION
	GROUP BY B.STATE,E.DATE
	HAVING DATEPART(YEAR,E.DATE) BETWEEN 2005 AND DATEPART(YEAR,GETDATE());

--Q1--END

--Q2--BEGIN
/*2. What state in the US is buying the most 'Samsung' cell phones?*/


    SELECT TOP 1 B.STATE
	FROM FACT_TRANSACTIONS E
	INNER JOIN DIM_MODEL D
	ON D.IDMODEL=E.IDMODEL
	INNER JOIN DIM_MANUFACTURER C
	ON D.IDMANUFACTURER = C.IDMANUFACTURER
	INNER JOIN DIM_LOCATION B
	ON B.IDLOCATION = E.IDLOCATION
	WHERE C.MANUFACTURER_NAME = 'SAMSUNG' AND B.COUNTRY = 'US'
	ORDER BY E.QUANTITY DESC;
	


--Q2--END

--Q3--BEGIN      
/*3. Show the number of transactions for each model per zip code per state. */


	
	SELECT D.MODEL_NAME,
		   COUNT(E.IDCUSTOMER) AS TRANSACTIONS,
		   B.ZIPCODE,
		   B.[STATE]
	FROM FACT_TRANSACTIONS E
	JOIN DIM_MODEL D
	ON E.IDMODEL = D.IDMODEL
	JOIN DIM_LOCATION B
	ON E.IDLOCATION = B.IDLOCATION
	GROUP BY D.MODEL_NAME,B.ZIPCODE,B.[STATE];

--Q3--END

--Q4--BEGIN
/*4. Show the cheapest cellphone (Output should contain the price also)*/


	SELECT TOP 1 MODEL_NAME,MIN(UNIT_PRICE) PRICE FROM DIM_MODEL
	GROUP BY MODEL_NAME;

	---OR----

	SELECT TOP 1 MODEL_NAME,
			UNIT_PRICE
	FROM  DIM_MODEL
	ORDER BY UNIT_PRICE;
	


--Q4--END

--Q5--BEGIN
/*5. Find out the average price for each model in the top5 manufacturers in 
terms of sales quantity and order by average price.*/




	SELECT T1.MANUFACTURER_NAME,T2.MODEL_NAME
	,AVG(T2.TOTALPRICE) AVG_PRICE
	FROM
	(SELECT TOP 5 C.MANUFACTURER_NAME,C.IDMANUFACTURER
--	,AVG(E.TOTALPRICE)
	,SUM(E.QUANTITY)  QTY
	FROM FACT_TRANSACTIONS E
	JOIN DIM_MODEL D
	ON E.IDMODEL = D.IDMODEL
	JOIN DIM_MANUFACTURER C
	ON C.IDMANUFACTURER=D.IDMANUFACTURER
	GROUP BY C.MANUFACTURER_NAME,C.IDMANUFACTURER
	ORDER BY QTY DESC
	)T1
	INNER JOIN
	(SELECT E.IDMODEL,D.MODEL_NAME,D.IDMANUFACTURER,E.TOTALPRICE 
	FROM FACT_TRANSACTIONS E
    JOIN DIM_MODEL D
	ON E.IDMODEL = D.IDMODEL)T2
	ON T1.IDMANUFACTURER=T2.IDMANUFACTURER
	GROUP BY T1.MANUFACTURER_NAME,T2.MODEL_NAME

	


--Q5--END

--Q6--BEGIN
/*6. List the names of the customers and the average amount spent in 2009, 
where the average is higher than 500 */


	SELECT  A.CUSTOMER_NAME,AVG(E.TOTALPRICE ) AVG_PRICE
	FROM FACT_TRANSACTIONS E
	INNER JOIN DIM_CUSTOMER A
	ON E.IDCUSTOMER=A.IDCUSTOMER
	WHERE DATEPART(YEAR,E.DATE)=2009
	GROUP BY A.CUSTOMER_NAME,DATEPART(YEAR,E.DATE)
	HAVING AVG(E.TOTALPRICE)>500
	ORDER BY AVG_PRICE DESC



--Q6--END
	
--Q7--BEGIN  
/*7. List if there is any model that was in the top 5 in terms of quantity, 
simultaneously in 2008, 2009 and 2010 */
	
	

WITH TL_1 AS(
	SELECT D.MODEL_NAME,SUM(QUANTITY) QTY,DATEPART(YEAR,E.DATE) DT
	FROM FACT_TRANSACTIONS E
	JOIN DIM_MODEL D
	ON E.IDMODEL = D.IDMODEL
	GROUP BY D.MODEL_NAME, DATEPART(YEAR,E.DATE)
	HAVING DATEPART(YEAR,E.DATE) in (2008,2009,2010)
	)

	SELECT S1.MODEL_NAME FROM
	(
	SELECT TOP 5 TL_1.MODEL_NAME,SUM(TL_1.QTY) QTY  FROM TL_1
	WHERE  TL_1.DT=2008
	GROUP BY MODEL_NAME
	ORDER BY SUM(TL_1.QTY) DESC
	)S1

	INTERSECT

	SELECT S2.MODEL_NAME FROM
	(
	SELECT TOP 5 TL_1.MODEL_NAME,SUM(TL_1.QTY) QTY FROM TL_1
	WHERE  TL_1.DT=2009
	GROUP BY MODEL_NAME
	ORDER BY SUM(TL_1.QTY) DESC
	)S2

	INTERSECT

	SELECT S3.MODEL_NAME FROM
	(
	SELECT TOP 5 TL_1.MODEL_NAME,SUM(TL_1.QTY) QTY FROM TL_1
	WHERE  TL_1.DT=2008
	GROUP BY MODEL_NAME
	ORDER BY SUM(TL_1.QTY) DESC
	)S3




--Q7--END	

--Q8--BEGIN
/*8. Show the manufacturer with the 2nd top sales in the year of 2009 and the 
manufacturer with the 2nd top sales in the year of 2010. */



	SELECT T2.MANUFACTURER_NAME,T2.[YEAR] FROM
	(
	SELECT C.MANUFACTURER_NAME,DATEPART(YEAR,E.DATE) [YEAR],SUM(TOTALPRICE) TOTAL_PRICE,RANK() OVER(PARTITION BY DATEPART(YEAR,E.DATE) ORDER BY SUM(TOTALPRICE) DESC) RNK
	FROM FACT_TRANSACTIONS E
	JOIN DIM_MODEL D
	ON E.IDMODEL = D.IDMODEL
	JOIN DIM_MANUFACTURER C
	ON D.IDMANUFACTURER = C.IDMANUFACTURER
	GROUP BY C.MANUFACTURER_NAME,DATEPART(YEAR,E.DATE)
	HAVING DATEPART(YEAR,E.DATE) IN (2010,2009))T2
	WHERE RNK=2




--Q8--END

--Q9--BEGIN
/*9. Show the manufacturers that sold cellphones in 2010 but did not in 2009*/

	SELECT * FROM
	(
	SELECT DISTINCT C.MANUFACTURER_NAME
	FROM FACT_TRANSACTIONS E
	JOIN DIM_MODEL D
	ON E.IDMODEL=D.IDMODEL
	JOIN DIM_MANUFACTURER C
	ON D.IDMANUFACTURER=C.IDMANUFACTURER
	GROUP BY C.MANUFACTURER_NAME,E.DATE
	HAVING DATEPART(YEAR,E.DATE)=2010
	)T1
	EXCEPT
	SELECT * FROM
	(
	SELECT DISTINCT C.MANUFACTURER_NAME
	FROM FACT_TRANSACTIONS E
	JOIN DIM_MODEL D
	ON E.IDMODEL=D.IDMODEL
	JOIN DIM_MANUFACTURER C
	ON D.IDMANUFACTURER=C.IDMANUFACTURER
	GROUP BY C.MANUFACTURER_NAME,E.DATE
	HAVING DATEPART(YEAR,E.DATE)=2009
	)T2
	


--Q9--END

--Q10--BEGIN
/*10. Find top 100 customers and their average spend, average quantity by each 
year. Also find the percentage of change in their spend.*/


SELECT T2.CUSTOMER_NAME,T1.YEAR_,T1.AVG_QTY,T1.AVG_SPEND,T1.TOTAL_SPEND,
(T1.TOTAL_SPEND-LAG(T1.TOTAL_SPEND,1) OVER(PARTITION BY T1.IDCUSTOMER ORDER BY T1.YEAR_))*100/LAG(T1.TOTAL_SPEND,1) OVER(PARTITION BY T1.IDCUSTOMER ORDER BY T1.YEAR_) PERCENT_CHANGE_SPEND
FROM(
	SELECT IDCUSTOMER,DATEPART(YEAR,DATE) YEAR_,AVG(QUANTITY) AVG_QTY,AVG(TOTALPRICE) AVG_SPEND,SUM(TOTALPRICE) AS TOTAL_SPEND
	FROM FACT_TRANSACTIONS
	GROUP BY IDCUSTOMER,DATEPART(YEAR,DATE)
	)T1
	JOIN DIM_CUSTOMER T2
	ON T1.IDCUSTOMER=T2.IDCUSTOMER
	
	



--Q10--END
	


	













